// Generated by Wrangler

import { D1Database } from "@cloudflare/workers-types/experimental";

// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    ACTIVE_DB: D1Database;
}
